### ISSUE TITLE
The package.json file is out-of-date

### ISSUE THREAD

**Issue by arbitrary-kdawg** [arbitraryexecution/forta-uma-suite#2]
The package.json file is out-of-date:

"forta-agent": "^0.0.11"

We want to use the latest agent for the UMA suite.

_Originally posted by @arbitrary-kdawg in https://github.com/arbitraryexecution/forta-uma-suite/issues/1#issuecomment-924435600_

**Comment by arbitrary-cr0** [comment]
`package.json` updated to 0.0.15 in https://github.com/arbitraryexecution/forta-uma-suite/pull/1
